name: 'Generate Contributors Jobs'

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13' 


      - name: Generate contributors page
        run: python generate_page.py


      - name: Check generated index.html
        run: |
          ls -la
          test -f ./dist/index.html


      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static file
        id: statics
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
